language: python
python:
    - "2.7"
install:
    - "pip install -r requirements-travis.txt --use-mirrors"
    - "pip install pep8 nose coverage mock"
script:
    - "pep8 replugin/"
notifications:
    email: false
